### PR TITLE
Added error handling

### PR DESCRIPTION
**Pull request by Nyholm**
This will allow us to have proper error handling like other transports. 

```
            workqueue:
              dsn: '%env(WORKQUEUE_DSN)%'
              retry_strategy:
                  max_retries: 3
                  # milliseconds delay
                  delay: 1000
                  multiplier: 2
                  max_delay: 60
```

### CODE REVIEW

**Comment by Nyholm** [comment]
Note that delay will not work with FIFO queues. 

But error handling works without specifying delays (or retries).

**Comment by mnapoli** [comment]
I'm not sure I understand, but I think this is about restoring the error handling from Symfony Messenger in this package.

If that's the case, that is not what we want. We intentionally want to skip error handling and retry mechanism from Symfony, because we don't need them.

SQS already handles all of that. We can configure retries and error handling on the queue, and avoid doing that ourselves.

Does that make sense? I should probably try to document that in the README.

**Comment by Nyholm** [comment]
> I'm not sure I understand, but I think this is about restoring the error handling from Symfony Messenger in this package.

You are correct. 

> If that's the case, that is not what we want. We intentionally want to skip error handling and retry mechanism from Symfony, because we don't need them.
SQS already handles all of that. We can configure retries and error handling on the queue, and avoid doing that ourselves.

I must not understand how that works then. 
I tried it out without this patch. If an exception is thrown in my handler, the message will indeed go back to the queue and be retried within a few seconds. So sure.. no message disappear and that is a kind of error handling. 

With this patch, I can configure the failure strategy in Symfony. Which means that I can retry a message X times and then put it in a database (or a different queue). 

So yes, This PR introduce the "Symfony way" of doing things.

**Comment by mnapoli** [comment]
I don't have much time at the moment to detail how SQS can be configured, but yes SQS does all of that.

Here is an example from a project:

```php
    queue:
        Type: AWS::SQS::Queue
        Properties:
            # This needs to be at least 6 times the lambda function's timeout
            # See https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
            VisibilityTimeout: '960'
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
                # Jobs will be retried 5 times
                # The number needs to be at least 5 per https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
                maxReceiveCount: 5
    # The dead letter queue is a SQS queue that receives messages that failed to be processed
    DeadLetterQueue:
        Type: AWS::SQS::Queue
        Properties:
            # Messages are stored up to 14 days (the max)
            MessageRetentionPeriod: 1209600
```

You can even use SNS to set up alerting in case the DLQ is used.

**Comment by Nyholm** [comment]
I see. I feel like I am more comfortable with the "symfony way". 

This PR can easily be made as "opt-in". Do you mind if the current functionality is kept as is and you can opt-in to this "symfony way"?

**Comment by Nyholm** [comment]
Closing in favor of: https://github.com/Nyholm/bref-symfony-messenger

**Pull request closed without merging**
